version: 2.27.0
services:
  marketlab-back:
    build: .
    ports:
      - "5555:3000"
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: "marketlab-redis"
    networks:
      - backend

  marketlab-redis:
    image: redis:latest
    networks:
      - backend

networks:
  backend:
    external: false